import type { Metadata } from "next";

import Head from "next/head";
import "./globals.css";
import Header from "./components/ui/header/Header";

export const metadata: Metadata = {
  title: "Sara.O.Weddings",
  description: "Generated by create next app",
  icons: ["/images/s_logo.png"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,100..900;1,9..144,100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap"
          rel="stylesheet"
        />
        <link
          rel="preload"
          as="video"
          href="/videos/hero.mp4"
          type="video/mp4"
        />
      </Head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
